'use client';

import { useState } from 'react';
import { useConnection, useWallet } from '@solana/wallet-adapter-react';
import { BN } from '@coral-xyz/anchor';
import { PublicKey, SystemProgram } from '@solana/web3.js';
import { useGigBoardProgram } from '../hooks/useGigBoardProgram'; // Generated by scaffold
import { toast } from 'react-hot-toast';

export function CreateBountyForm() {
  const { connection } = useConnection();
  const { program } = useGigBoardProgram();
  const { publicKey, sendTransaction } = useWallet();
  const [title, setTitle] = useState('');
  const [price, setPrice] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async () => {
    if (!publicKey || !program) return;
    setLoading(true);

    try {
      const id = new BN(Date.now()); // Unique ID based on timestamp
      const priceLamports = new BN(parseFloat(price) * 1000000000); // Convert SOL to Lamports

      // Derive PDA client-side
      const [bountyPda] = PublicKey.findProgramAddressSync(
        [Buffer.from('bounty'), publicKey.toBuffer(), id.toArrayLike(Buffer, 'le', 8)],
        program.programId
      );

      const tx = await program.methods
        .postBounty(id, priceLamports, title)
        .accounts({
          bounty: bountyPda,
          poster: publicKey,
          systemProgram: SystemProgram.programId,
        })
        .transaction();

      const signature = await sendTransaction(tx, connection);
      toast.success(`Bounty Posted! Sig: ${signature.slice(0, 8)}...`);
      setTitle('');
      setPrice('');
    } catch (error) {
      console.error(error);
      toast.error("Failed to post bounty");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 bg-slate-800 rounded-xl border border-slate-700">
      <h2 className="text-xl font-bold mb-4 text-white">Post a New Gig</h2>
      <input 
        type="text" 
        placeholder="Task Description" 
        className="w-full mb-2 p-2 rounded bg-slate-900 text-white"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />
      <input 
        type="number" 
        placeholder="Price in SOL" 
        className="w-full mb-4 p-2 rounded bg-slate-900 text-white"
        value={price}
        onChange={(e) => setPrice(e.target.value)}
      />
      <button 
        onClick={handleSubmit}
        disabled={loading}
        className="bg-purple-600 hover:bg-purple-500 text-white px-4 py-2 rounded font-bold w-full disabled:opacity-50"
      >
        {loading ? 'Processing...' : 'Lock Funds & Post'}
      </button>
    </div>
  );
}

// 'use client';

// import { useState } from 'react';
// import { useConnection, useWallet } from '@solana/wallet-adapter-react';
// import { BN } from '@coral-xyz/anchor';
// import { PublicKey, SystemProgram, Keypair } from '@solana/web3.js';
// import { 
//     getAssociatedTokenAddress, 
//     TOKEN_PROGRAM_ID, 
//     ASSOCIATED_TOKEN_PROGRAM_ID, 
//     getMint 
// } from "@solana/spl-token";
// import { useGigBoardProgram } from '../hooks/useGigBoardProgram';
// import { toast } from 'react-hot-toast';

// // ⚠️ REPLACE THIS WITH YOUR MOCK MINT ADDRESS AFTER YOU CREATE ONE
// const USDC_MINT = new PublicKey("DmSzem8n3mVDJobzoexKRf9PVzXMUCh8JDtggr4W8FqE"); 

// export function CreateBountyForm() {
//   const { connection } = useConnection();
//   const { program } = useGigBoardProgram();
//   const { publicKey, sendTransaction } = useWallet();
  
//   const [title, setTitle] = useState('');
//   const [price, setPrice] = useState('');
//   const [loading, setLoading] = useState(false);

//   const handleSubmit = async () => {
//     if (!publicKey || !program) return;
//     setLoading(true);

//     try {
//       const id = new BN(Date.now());
//       // USDC has 6 decimals, not 9 like SOL
//       const priceUSDC = new BN(parseFloat(price) * 1000000); 

//       // 1. Derive Bounty PDA
//       const [bountyPda] = PublicKey.findProgramAddressSync(
//         [Buffer.from('bounty'), publicKey.toBuffer(), id.toArrayLike(Buffer, 'le', 8)],
//         program.programId
//       );

//       // 2. Derive Bounty Vault PDA (Where the money goes)
//       const [vaultPda] = PublicKey.findProgramAddressSync(
//         [Buffer.from('vault'), bountyPda.toBuffer()],
//         program.programId
//       );

//       // 3. Get User's Token Account (Source of funds)
//       const userTokenAccount = await getAssociatedTokenAddress(
//         USDC_MINT,
//         publicKey
//       );

//       // 4. Send Transaction
//       const tx = await program.methods
//         .postBounty(id, priceUSDC, title, publicKey) // 'publicKey' here is the Arbiter (Self for V1)
//         .accounts({
//           bounty: bountyPda,
//           bountyVault: vaultPda,
//           posterTokenAccount: userTokenAccount,
//           mint: USDC_MINT,
//           poster: publicKey,
//           systemProgram: SystemProgram.programId,
//           tokenProgram: TOKEN_PROGRAM_ID,
//           rent: new PublicKey("SysvarRent111111111111111111111111111111111"),
//         })
//         .transaction();

//       const signature = await sendTransaction(tx, connection);
//       toast.success("Gig Posted with USDC!");
      
//     } catch (error) {
//       console.error(error);
//       toast.error("Failed. Do you have Mock USDC?");
//     } finally {
//       setLoading(false);
//     }
//   };

//   return (
//     <div className="p-6 bg-slate-800 rounded-xl border border-slate-700">
//       <h2 className="text-xl font-bold mb-4 text-white">Post a New Gig (USDC)</h2>
//       {/* Input fields same as before... */}
//       <input 
//         type="text" 
//         placeholder="Task Description" 
//         className="w-full mb-2 p-2 rounded bg-slate-900 text-white"
//         value={title}
//         onChange={(e) => setTitle(e.target.value)}
//       />
//       <input 
//         type="number" 
//         placeholder="Price in USDC" 
//         className="w-full mb-4 p-2 rounded bg-slate-900 text-white"
//         value={price}
//         onChange={(e) => setPrice(e.target.value)}
//       />
//       <button 
//         onClick={handleSubmit}
//         disabled={loading}
//         className="bg-green-600 hover:bg-green-500 text-white px-4 py-2 rounded font-bold w-full"
//       >
//         {loading ? 'Processing...' : 'Post 500 USDC Gig'}
//       </button>
//     </div>
//   );
// }